language: go
go:
 - "1.13"
after_success:
 - go get github.com/mattn/goveralls
 - "go test -v -covermode=count -coverprofile=coverage.out"
 - "goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN"
